TEXT = {
    "ru": {
        "start_message": "Здравствуйте! Выберите язык.",
        "main_menu": "Главное меню:",
        "about_college": "О колледже",
        "working_hours": "График приёма",
        "contacts": "Контакты",
        "specialties": "Специальности",
        "documents": "Документы для поступления",
        "faq": "Вопросы и ответы",
        "back": "Назад",
        "change_language": "🌍 Сменить язык",
        "admin_menu": "Меню администратора",
        "moderator_menu": "Меню модератора",
        "ban_user": "Забанить пользователя",
        "unban_user": "Разбанить пользователя",
        "add_moderator": "Добавить модератора",
        "remove_moderator": "Удалить модератора",
        "edit_content": "Редактировать контент",
        "ask_question": "Задать вопрос",
        "view_questions": "Посмотреть вопросы",
        "budget_learning": "Бюджетное обучение",
        "paid_learning": "Платное обучение",
        "rules": "Правила приёма",
        "banned": "Вы забанены и не можете использовать бота.",
        "change_user_role": "Изменить роль пользователя",
        "change_own_role": "Изменить свою роль",
        "leave_review": "Оставить отзыв",
        "view_reviews": "Посмотреть отзывы",
        "show_map": "🗺️ Показать на карте"  # Новая строка
    },
    "en": {
        "start_message": "Hello! Please select a language.",
        "main_menu": "Main Menu:",
        "about_college": "About College",
        "working_hours": "Admission Schedule",
        "contacts": "Contacts",
        "specialties": "Specialties",
        "documents": "Documents for Admission",
        "faq": "Questions and Answers",
        "back": "Back",
        "change_language": "🌍 Change language",
        "admin_menu": "Admin Menu",
        "moderator_menu": "Moderator Menu",
        "ban_user": "Ban User",
        "unban_user": "Unban User",
        "add_moderator": "Add Moderator",
        "remove_moderator": "Remove Moderator",
        "edit_content": "Edit Content",
        "ask_question": "Ask a Question",
        "view_questions": "View Questions",
        "budget_learning": "Budget Learning",
        "paid_learning": "Paid Learning",
        "rules": "Admission Rules",
        "banned": "You are banned and cannot use the bot.",
        "change_user_role": "Change User Role",
        "change_own_role": "Change Own Role",
        "leave_review": "Leave a Review",
        "view_reviews": "View Reviews",
        "show_map": "🗺️ Show on Map"  # Новая строка
    },
    "uz": {
        "start_message": "Assalomu alaykum! Tilni tanlang.",
        "main_menu": "Asosiy menyular:",
        "about_college": "Kolleja haqida",
        "working_hours": "Qabul jadvali",
        "contacts": "Aloqa ma'lumotlari",
        "specialties": "Mutaxassisliklar",
        "documents": "Qabul uchun hujjatlar",
        "faq": "Savollar va javoblar",
        "back": "Orqaga",
        "change_language": "🌍 Tilni o'zgartirish",
        "admin_menu": "Administrator menyusi",
        "moderator_menu": "Moderator menyusi",
        "ban_user": "Foydalanuvchini bloklash",
        "unban_user": "Foydalanuvchini blokdan chiqarish",
        "add_moderator": "Moderator qo'shish",
        "remove_moderator": "Moderatorni o'chirish",
        "edit_content": "Kontentni tahrirlash",
        "ask_question": "Savol berish",
        "view_questions": "Savollarni ko'rish",
        "budget_learning": "Budjet ta'limi",
        "paid_learning": "Pullik ta'lim",
        "rules": "Qabul qoidalari",
        "banned": "Siz bloklangansiz va botdan foydalana olmaysiz.",
        "change_user_role": "Foydalanuvchi rolini o'zgartirish",
        "change_own_role": "O'z rolingizni o'zgartirish",
        "leave_review": "Fikr qoldirish",
        "view_reviews": "Fikrlarni ko'rish",
        "show_map": "🗺️ Xaritada ko'rsatish"  # Новая строка
    },
    "ky": {
        "start_message": "Саламатсызбы! Тилди тандаңыз.",
        "main_menu": "Негизги меню:",
        "about_college": "Колледж жөнүндө",
        "working_hours": "Кабыл алуу графиги",
        "contacts": "Байланыш маалыматтары",
        "specialties": "Адистиктер",
        "documents": "Кабыл алуу үчүн документтер",
        "faq": "Суроолор жана жооптор",
        "back": "Артка",
        "change_language": "🌍 Тилди өзгөртүү",
        "admin_menu": "Администратор менюсу",
        "moderator_menu": "Модератор менюсу",
        "ban_user": "Колдонуучуну бөгөттөө",
        "unban_user": "Колдонуучуну бөгөттөн чыгаруу",
        "add_moderator": "Модератор кошуу",
        "remove_moderator": "Модераторду алып салуу",
        "edit_content": "Мазмунду түзөтүү",
        "ask_question": "Суроо берүү",
        "view_questions": "Суроолорду көрүү",
        "budget_learning": "Бюджеттик окуу",
        "paid_learning": "Акы төлөнүүчү окуу",
        "rules": "Кабыл алуу эрежелери",
        "banned": "Сиз бөгөттөлдүңүз жана ботту колдоно албайсыз.",
        "change_user_role": "Колдонуучунун ролун өзгөртүү",
        "change_own_role": "Өз ролуңузду өзгөртүү",
        "leave_review": "Пикир калтыруу",
        "view_reviews": "Пикирлерди көрүү",
        "show_map": "🗺️ Картада көрсөтүү"  # Новая строка
    },
    "tg": {
        "start_message": "Салом! Забонро интихоб кунед.",
        "main_menu": "Менюи асосӣ:",
        "about_college": "Дар бораи коллеҷ",
        "working_hours": "Ҷадвали қабул",
        "contacts": "Тамосҳо",
        "specialties": "Ихтисосҳо",
        "documents": "Ҳуҷҷатҳо барои қабул",
        "faq": "Саволҳо ва ҷавобҳо",
        "back": "Бозгашт",
        "change_language": "🌍 Тағйири забон",
        "admin_menu": "Менюи администратор",
        "moderator_menu": "Менюи модератор",
        "ban_user": "Манъ кардани корбар",
        "unban_user": "Аз манъ озод кардани корбар",
        "add_moderator": "Илова кардани модератор",
        "remove_moderator": "Хориҷ кардани модератор",
        "edit_content": "Таҳрири мундариҷа",
        "ask_question": "Савол додан",
        "view_questions": "Дидани саволҳо",
        "budget_learning": "Таҳсили буҷетӣ",
        "paid_learning": "Таҳсили пулакӣ",
        "rules": "Қоидаҳои қабул",
        "banned": "Шумо манъ шудаед ва наметавонед ботро истифода баред.",
        "change_user_role": "Тағйири нақши корбар",
        "change_own_role": "Тағйири нақши худ",
        "leave_review": "Фикр гузоштан",
        "view_reviews": "Фикрҳоро дидан",
        "show_map": "🗺️ Дар харита нишон додан"  # Новая строка
    }
}

def get_text(language, key):
    return TEXT.get(language, TEXT["ru"]).get(key, "Текст не найден")